spring:
  application:
    name: api-Livraria
  datasource:
    url: jdbc:postgresql://localhost:5432/livraria
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver